### ISSUE TITLE
Workflow disappear after changing routes

### ISSUE THREAD

**Issue by FukutoTojido** [nguyendhst/low-code-monorepo#65]

**Comment by ngnhng** [comment]
@FukutoTojido  I'm stuck 💀. Pls help.

Code are at branch [bug](https://github.com/nguyendhst/low-code-monorepo/tree/bug/workflow/load-wf)

**Comment by ngnhng** [comment]
Modeler is attached to the correct `<div` but soft navigation and/or caching (fuck next.js for this) somehow messes up the subsequent render.
